Remove name requirement for CC/BCC
utopia-php/messaging pull request #87
Opened 2024-10-07 03:53 UTC by abnegate

## What does this PR do?

Remove requirement for a name for CC/BCC for emails

## Test Plan
Updated existing tests

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/utopia-php/messaging/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2024-10-08 18:58 UTC, byawitz requested changes

2024-10-08 18:58 UTC, byawitz commented on src/Utopia/Messaging/Adapter/Email/Mailgun.php
> +                    $body['cc'] = !empty($body['cc'])
This should be `$body['bcc']` ?

2024-10-09 02:16 UTC, abnegate commented on src/Utopia/Messaging/Adapter/Email/Mailgun.php
> +                    $body['cc'] = !empty($body['cc'])
Yep, fixed

2024-10-09 02:34 UTC, byawitz approved these changes

2024-10-09 08:17 UTC, merged